# Generated by Django 4.2.13 on 2024-11-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='header',
        ),
        migrations.AddField(
            model_name='header',
            name='description',
            field=models.TextField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='header',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='header',
            name='redSocial',
            field=models.TextField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='telephone',
            field=models.TextField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='ubication',
            field=models.TextField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='urlImage',
            field=models.TextField(blank=True, default=dict, null=True),
        ),
    ]
