# Generated by Django 4.2.13 on 2024-11-25 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('header', '0002_remove_header_header_header_description_header_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='header',
            name='name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='header',
            name='posted_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='header',
            name='redSocial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='telephone',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='ubication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='urlImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
