# Generated by Django 4.2.13 on 2024-11-19 18:10

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(default='')),
                ('year_start', models.IntegerField(blank=True, default=2024)),
                ('year_end', models.IntegerField(blank=True, default=2024)),
                ('work', models.TextField(blank=True, default=dict, null=True)),
                ('position', models.TextField(blank=True, default=dict, null=True)),
                ('achievements', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
