# Generated by Django 4.2.13 on 2024-11-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexperience', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='achievements',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='achievments',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
